os:
  - linux
  - osx

dist: xenial

language: go

env:
  - GO111MODULE=on

sudo: true

go:
  - 1.12.x
  - 1.13.x
  - master

git:
  depth: 3

install: true

notifications:
  email: false

script:
  - sudo -E env "PATH=$PATH" go test -v -race .